export enum ActionsTypes {
  SET_STATE = 'SET_STATE',
  SET_SCREEN = 'SET_SCREEN',
  ADD_CARD = 'ADD_CARD',
  DELETE_CARD = 'DELETE_CARD',
  ADD_TRANSACTION = 'ADD_TRANSACTION',
  SET_ACTIVE_CARD = 'SET_ACTIVE_CARD',
  UPDATE_BALANCE = 'UPDATE_BALANCE',
  SHOW_MODAL = 'SHOW_MODAL',
  HIDE_MODAL = 'HIDE_MODAL',
}
