export enum ActionsTypes {
  ADD_NEW_CARD = 'ADD_NEW_CARD',
  ADD_TRANSACTION = 'ADD_TRANSACTION',
  SET_ACTIVE_CARD = 'SET_ACTIVE_CARD',
  UPDATE_BALANCE = 'UPDATE_BALANCE',
  SHOW_MODAL = 'SHOW_MODAL',
  HIDE_MODAL = 'HIDE_MODAL',
}
